[build]
  publish = "dist"
  command = "npm ci && npm run build"

[[redirects]]
  from = "/api/*"
  to = "http://e1.chiasegpu.vn:25232/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "http://e1.chiasegpu.vn:25232/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/minio/*"
  to = "http://e1.chiasegpu.vn:25232/api/uploads/minio-legacy/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
