[build]
  base = "frontend"
  publish = "dist"
  command = "npm ci && npm run build"

[[redirects]]
  from = "/api/*"
  to = "http://160.250.5.197:8081/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "http://160.250.5.197:8081/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/minio/*"
  to = "http://160.250.5.197:8081/api/uploads/minio-legacy/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "http://160.250.5.197:8081/api/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "http://160.250.5.197:8081/auth/:splat"
  status = 200

[[redirects]]
  from = "/minio/*"
  to = "http://160.250.5.197:8081/api/uploads/minio-legacy/:splat"
  status = 200


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
