spring.application.name=cutie-cuts-app
spring.datasource.url=jdbc:postgresql://localhost:5432/haircut_db
spring.datasource.username=postgres
spring.datasource.password=04012006

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081